src/cart/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    CartView,
    CartApiViewSet,
    SellerApiViewSet,
    CreateOrderView,
    OrderListView,
    OrderDetailView,
)

app_name = "cart"

router = DefaultRouter()
router.register(r'cart', CartApiViewSet, basename='cart_api')
router.register(r'product-seller', SellerApiViewSet, basename='product_seller_api')

urlpatterns = [
    path('', CartView.as_view(), name='cart_view'),
    path('api/', include(router.urls)),
    path('order_list/', OrderListView.as_view(), name='order_list'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
]

src/megano/urls.py
"""
URL configuration for megano project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an product_import:  from my_app product_import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an product_import:  from other_app.views product_import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls product_import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

from products.views import IndexView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('payment/', include('payments.urls')),
]

urlpatterns += i18n_patterns(
    path('account/', include('account.urls')),
    path('sale/', include('discounts.urls')),
    path('cart/', include('cart.urls')),
    path('catalog/', include('products.urls')),
    path('', IndexView.as_view(), name='index'),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns.extend(
        static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT
        )
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

src/catalog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from account.models import Profile
from products.models import Product


class Review(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    text = models.TextField(max_length=1000, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='reviews',
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Review')
        verbose_name_plural = _('Reviews')

src/catalog/forms.py
from django.forms import ModelForm

from catalog.models import Review

class ReviewForm(ModelForm):

    class Meta:
        model = Review
        fields = 'text',

src/templates/catalog/catalog.jinja2
{% extends 'base.jinja2' %}

{% block title %}
    Megano
{% endblock %}

{% block header %}
    {% include 'common/header_full.jinja2' %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">{% trans %}Фильтр{% endtrans %}
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        {% if filter_form %}
                            <form class="form" action="?" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <div class="range Section-columnRange">
                                        {{ filter_form.price }}
                                        <div class="range-price">{% trans %}Цена:{% endtrans %}&#32;
                                            <div class="rangePrice">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        {{ filter_form.title }}
                                    </div>
                                    <div class="form-group">
                                        <label class="toggle">
                                            {{ filter_form.in_stock }}
                                            <span class="toggle-box"></span><span class="toggle-text">{% trans %}Только товары в наличии{% endtrans %}</span>
                                        </label>
                                    </div>
                                    <div class="form-group">
                                        <div class="buttons">
                                            <input class="btn btn_square btn_dark btn_narrow" type="submit" value="{% trans %}Фильтр{% endtrans %}">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="Section-columnSection">
                    {% if tags %}
                        <header class="Section-header">
                            <strong class="Section-title">{% trans %}Популярные тэги{% endtrans %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="buttons">
                                {% for tag in tags %}
                                    <a class="btn btn_default btn_sm" href="{{ tag.get_absolute_url() }}">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="Section-content">
                <div class="Sort">
                        <div class="Sort-title">{% trans %}Сортировать по:{% endtrans %}
                        </div>
                        <div class="Sort-variants">
                            <a class="Sort-sortBy {% if curr_sort and curr_sort == sort.POP_ASC.value %}
Sort-sortBy_inc
{% elif curr_sort and curr_sort == sort.POP_DEC.value %}
Sort-sortBy_dec
{% endif %}"
                               href="?sort={% if curr_sort and curr_sort == sort.POP_ASC.value %}
{{ sort.POP_DEC.value }}
{% elif curr_sort and curr_sort == sort.POP_DEC.value %}
{{ sort.NONE.value }}
{% else %}
{{ sort.POP_ASC.value }}
                                           {% endif %}">
                                {% trans %}Популярности{% endtrans %}
                            </a>
                            <a class="Sort-sortBy {% if curr_sort and curr_sort == sort.PRI_ASC.value %}
Sort-sortBy_inc
{% elif curr_sort and curr_sort == sort.PRI_DEC.value %}
Sort-sortBy_dec
{% endif %}"
                               href="?sort={% if curr_sort and curr_sort == sort.PRI_DEC.value %}
{{ sort.PRI_ASC.value }}
{% elif curr_sort and curr_sort == sort.PRI_ASC.value %}
{{ sort.NONE.value }}
{% else %}
{{ sort.PRI_DEC.value }}
                                           {% endif %}">
                                {% trans %}Цене{% endtrans %}
                            </a>
                            <a class="Sort-sortBy {% if curr_sort and curr_sort == sort.REV_ASC.value %}
Sort-sortBy_inc
{% elif curr_sort and curr_sort == sort.REV_DEC.value %}
Sort-sortBy_dec
{% endif %}"
                               href="?sort={% if curr_sort and curr_sort == sort.REV_ASC.value %}
{{ sort.REV_DEC.value }}
{% elif curr_sort and curr_sort == sort.REV_DEC.value %}
{{ sort.NONE.value }}
{% else %}
{{ sort.REV_ASC.value }}
                                           {% endif %}">
                                {% trans %}Отзывам{% endtrans %}
                            </a>
                            <a class="Sort-sortBy {% if curr_sort and curr_sort == sort.CRE_ASC.value %}
Sort-sortBy_inc
{% elif curr_sort and curr_sort == sort.CRE_DEC.value %}
Sort-sortBy_dec
{% endif %}"
                               href="?sort={% if curr_sort and curr_sort == sort.CRE_ASC.value %}
{{ sort.CRE_DEC.value }}
{% elif curr_sort and curr_sort == sort.CRE_DEC.value %}
{{ sort.NONE.value }}
{% else %}
{{ sort.CRE_ASC.value }}
{% endif %}">
                                {% trans %}Новизне{% endtrans %}
                            </a>
                        </div>
                    </div>
                <div class="Cards">
                    {% for product in products %}
                        <div class="Card">
                            {% with picture = product.images.first() %}
                                {% if picture %}
                                    <a class="Card-picture" href="{{ product.get_absolute_url() }}">
                                        <img src="{{ picture.image.url }}" alt="Product image" />
                                    </a>
                                {% endif %}
                            {% endwith %}
                            <div class="Card-content">
                                <strong class="Card-title">
                                    <a href="{{ product.get_absolute_url() }}">{{ product.name }}</a>
                                </strong>
                                <div class="Card-description">
                                    {% with regular_price = product.average_price, discounted_price = product.discounted_average_price %}
                                        <div class="Card-cost">
                                            {% if discounted_price > 0 %}
                                                {% if regular_price != discounted_price %}
                                                    <span class="Card-priceOld">${{ regular_price }}</span>
                                                {% endif %}
                                                <span class="Card-price">${{ discounted_price }}</span>
                                            {% else %}
                                                <span class="Card-priceOutOfStock">{% trans %}Нет в наличии{% endtrans %}</span>
                                            {% endif %}
                                        </div>
                                        <div class="Card-category">
                                            {{ product.category.full_name }}
                                        </div>
                                        {% if discounted_price > 0 %}
                                            <div class="Card-hover">
                                                <a class="Card-btn" onclick="add_to_cart('{{ product.pk }}')">
                                                    <img src="{{ static('assets/img/icons/card/cart.svg') }}" alt="cart.svg" />
                                                </a>
                                            </div>
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                        </div>
                    {% else %}
                        {% trans %}Не найдено продуктов для отображения.{% endtrans %}
                    {% endfor %}
                </div>
                {% if products.has_other_pages() %}
                    <div class="Pagination">
                        <div class="Pagination-ins">
                            {% if products.has_previous() %}
                                <a class="Pagination-element Pagination-element_prev" href="?p={{ products.previous_page_number() }}">
                                    <img src="{{ static('assets/img/icons/prevPagination.svg') }}"  alt="prevPagination.svg" />
                                </a>
                            {% endif %}

                            {% if products.has_previous() and products.has_next() %}
                                {% set start = products.number - 2 %}
                                {% set end = products.number + 1 %}
                            {% elif products.has_previous() %}
                                {% set start = ([products.number - 3, 0]|max) %}
                                {% set end = products.number %}
                            {% else %}
                                {% set start = products.number - 1 %}
                                {% set end = products.number + 2 %}
                            {% endif %}

                            {% for page_num in products.paginator.page_range[start:end] %}
                                {% if page_num == products.number %}
                                    <span class="Pagination-element Pagination-element_current">
                                        <span class="Pagination-text">{{ page_num }}</span>
                                    </span>
                                {% else %}
                                    <a class="Pagination-element" href="?p={{ page_num }}">
                                        <span class="Pagination-text">{{ page_num }}</span>
                                    </a>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next() %}
                                <a class="Pagination-element Pagination-element_prev" href="?p={{ products.next_page_number() }}">
                                    <img src="{{ static('assets/img/icons/nextPagination.svg') }}" alt="nextPagination.svg" />
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/catalog/review.jinja2
{% block extra_css %}
    <link href="{{ static('assets/css/review.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="Tabs-block" id="reviews" style="">
        <header class="Section-header">
            <h3 class="Section-title">
                {{ get_count_review.1 }}
            </h3>
        </header>
        <div class="Comments">
            {% for review in reviews %}
                <div class="Comment">
                    <div class="Comment-column Comment-column_pict">
                        {% if review.author.avatar %}
                            <img src="{{ review.author.avatar.url }}" alt="Avatar" class="Comment-avatar-image">
                        {% else %}
                        <div class="Comment-avatar">
                        </div>
                        {% endif %}
                    </div>
                    <div class="Comment-column">
                        <header class="Comment-header">
                            <div>
                                <strong class="Comment-title">
                                    {{ review.author.first_name + ' ' + review.author.last_name }}
                                </strong>
                                <span class="Comment-date">
                                    {{ review.created_at.strftime('%d %B %Y / %H:%M') }}
                                </span>
                            </div>
                        </header>
                        <div class="Comment-content">
                            {{ review.text }}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if reviews %}
            <div class="Comment-more">
                <button class="btn-more btn btn_muted" id="btn-more">{% trans %}Показать еще{% endtrans %}</button>
            </div>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
            <header class="Section-header Section-header_product">
                <h3 class="Section-title">
                    {% trans %}Добавить отзыв{% endtrans %}
                </h3>
            </header>
            <div class="Tabs-addComment">
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-textarea" name="text" id="id_text" placeholder="{% trans %}Отзыв{% endtrans %}"></textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn btn_muted" type="submit">
                            {% trans %}Отправить отзыв{% endtrans %}
                        </button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{{ static('assets/js/review.js') }}"></script>

{% endblock %}

src/templates/catalog/review_pass.jinja2
{% extends 'base.jinja2' %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ static('assets/css/basic.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('assets/css/fonts.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('assets/css/extra.css') }}">
{% endblock %}

{% block header %}
    {% include 'common/header_parts/header_middle_full.jinja2' %}
    {% include 'common/header_parts/header_search.jinja2' %}
{% endblock %}

{% block content %}
    {% include review_template %} {#Пример включения шаблона добавления отзыва в код страницы#}
{% endblock %}